config/routes.rb
Rails.application.routes.draw do
  root 'pins#index'
  resources :pins #CREATES ALL RESTFUL ROUTES FOR RESOURCE
  # get '/pins', to: 'pins#index'
  # post '/pins', to: 'pins#create'
  # get '/pins/new', to: 'pins#new'
  # get '/pins/:id', to: 'pins#show', as: :pin
  # put '/pins/:id', to: 'pins#update'
  # patch '/pins/:id', to: 'pins#update'
  # get '/pins/:id/edit', to: 'pins#edit'
  # delete '/pins/:id', to: 'pins#destroy'
end

# http VERB 'route', to: 'controller#action'

app/models/pin.rb
class Pin < ActiveRecord::Base
  validates :url, :comment, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  def index
    @pins = Pin.all
    render :index
  end

  def new
    @pin = Pin.new
  end

  def create
    @pin = Pin.create pin_params
    redirect_to "/pins"
  end

  def show
    @pin = Pin.find(params[:id])
  end

  def edit 
    @pin = Pin.find(params[:id])
  end 

  def update
    @pin = Pin.find(params[:id])

    @pin.update(pin_params)
    redirect_to '/pins'
  end

  def destroy
    @pin = Pin.find(params[:id])
    @pin.destroy
    redirect_to '/'
  end

  private
  def pin_params
    params.require(:pin).permit(:url, :comment, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GPin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pins/_navbar.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>gPin</title>
</head>
<body class="container" style="padding-top: 60px">
  <nav class="navbar navbar-default navbar-fixed-top navbar transparent">
    <%= link_to 'gPin', pins_path(@pin), class: 'btn btn-info homeBtn' %>
    <!-- <a class="navbar-brand" href="/pins">gPin</a> -->
    <form class="navbar-form navbar-right" role="search" action="/searchresults">
      <div class="form-group">
        <%= link_to 'New Pin', new_pin_path(@pin), class: 'btn btn-default newBtn' %>
        <!-- <a href="/pins/new" class="btn btn-default newBtn">New Pin</a> -->
             <!-- <a href="/logout" class="btn btn-default">Log Out</a> -->
      </div>
    </form> 
  </nav>
</body>
</html>

app/views/pins/edit.html.erb
<%= render "navbar" %>

<h1>Edit Pin</h1>

<%= form_for @pin do |f| %>
  <%= f.label "Url" %>
  <%= f.text_field :url %><br />
  <%= f.label "Comment" %>
  <%= f.text_field :comment %><br />
  <%= f.label "Image" %>
  <%= f.text_field :image %><br />
  <%= f.submit "Edit Pin" %>

<% end %>

<%= link_to 'Destroy', @pin, method: :delete, data: {confirm: "Are you sure?"} %>

app/views/pins/index.html.erb
<%= render "navbar" %>

<h1>Pins</h1>

<table class="table table-striped">
  <thead class="">
    <td>IMG</td>
    <td>URL</td>
    <td>Comment</td>
    <td></td>
  </thead>
  <tbody>
<% @pins.each do |pin| %>
    <tr>
      <td><img src="<%= pin.image %>" style="width: 50px"></td>
      <td><a href="<%= pin.url %>"><%= pin.url %></a></td>
      <td> <%= pin.comment %></td>
      <td><%= link_to 'More', pin_path(pin), class: '' %></td>
    </tr>
<% end %>
  </tbody>
</table>

app/views/pins/new.html.erb
<%= render "navbar" %>

<h1>New Pin</h1>

<%= form_for @pin do |f| %>
<div class="form1">
  <%= f.label "Url" %>
  <%= f.text_field :url %>
</div> 
<div class="form1">
  <%= f.label "Comment" %>
  <%= f.text_field :comment %>
</div>   
<div class="form1">
  <%= f.label "Image" %>
  <%= f.text_field :image %>
</div>
  <%= f.submit "Submit" %>
<% end %>

app/views/pins/show.html.erb
<%= render "navbar" %>

<h1 class="text-center"><a href="<%= @pin.url %>"><%= @pin.url %></a></h1><br>
<div class="text-center">
  <img src="<%= @pin.image %>" style="width: 400px" class="text-center">
</div><br>
<p class="text-center"><%= @pin.comment %></p>

<div class="text-center">
  <%= link_to 'Edit this pin', edit_pin_path(@pin), class: 'btn btn-info' %> <!--LINK_TO PATH edit_pin_path(@pin) comes from route prefix-->
  <!-- <a class="btn btn-default" href="/pins/<%= @pin.id %>/edit" class="text-center" role="button">Edit</a> -->
  <div class="btn btn-default" role="button"><%= link_to 'Delete', @pin, method: :delete, data: {confirm: "Are you sure?"} %> <!--@pin == @pin_path rails automatically knows to follow @pin_path -->
  </div>
</div>